language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build FaeriaPatcher
before_deploy:
  - cd FaeriaPatcher/FaeriaPatcher/bin/Release/netcoreapp2.0/win10-x64/
  - zip -r FaeriaPatcher.zip .
deploy:
  provider: releases
  api_key:
    secure: QAptXqVJfJzJ0nrdpkd5sa45oupYktg11HeaH1/962LSrCw6woEuD3MsUcUJVlorNdJMoEhal/ywDq9+GPS7nJAkk3Dg8VROHmN81SE/eK+uEtC3ogk0JcJktfuvHeT5wWPxS9Pm+lBxB/YlfCNT4sXZzfZYL+G70jCPVgc8tTX5vGZo1PZeiMnhKa4wwTOjIpH/u5V5vQqzZVYHW2p0Re4Ez3qBU7fytgMiURc5GBr+dyGvaMnAcA3ewqLmdRc630Ih2bRhfBy8vfDqz6UGX78mICG3iU8DHHL4FTnAeJZDp/3LpMmZ8kV2o9abibyxsQaocBb3dcz9PTVwQTGtc6c0WBXfgXFHwoE+FcCcDatxI0QiL3x+xYdVl4pYnunNUyR1lE7vr3BnL8OabNlWIzqKFB/i4glf2WRyxu1CJCLI54FAP5mSO8tqBjcKDhgkKC6uedzFBnDp8yr7tKjpRth3zfiQzn6DdbUL0CBJovjGj4fZ56//3F1eSYiq0LygHfDPbeD6v16Sp4ED3V3jq92lVrC6w2x+2hJ61J4Owcs4qZL9fGqR9fdaT2pBdW5zNxTvEZHtK1zuJmCDCdAPnsvB01xIwJVpa8/W2u2tKEXmEKphEQB/Yfy0iRYjwTuG/Ex38kc9CRpF1GUqe8x+InvFhGX0tUj2SAoWH9A87eo=
  file: "./FaeriaPatcher/FaeriaPatcher/bin/Release/netcoreapp2.0/win10-x64/FaeriaPatcher.zip"
  skip_cleanup: true
  on:
    repo: aaa4xu/Faeria-Patcher
    tags: true
